from enum import StrEnum

"""公共枚举定义。"""


class MessageType(StrEnum):
    HELLO = "HELLO"
    REGISTER = "REGISTER"
    REGISTER_OK = "REGISTER_OK"
    REGISTER_REJECT = "REGISTER_REJECT"
    HEARTBEAT = "HEARTBEAT"
    PING = "PING"
    PONG = "PONG"
    GOODBYE = "GOODBYE"
    ERROR = "ERROR"
    WARN = "WARN"
    METRICS = "METRICS"
    SESSION_CREATE = "SESSION_CREATE"
    SESSION_START = "SESSION_START"
    SESSION_PAUSE = "SESSION_PAUSE"
    SESSION_RESUME = "SESSION_RESUME"
    SESSION_STOP = "SESSION_STOP"
    SESSION_ABORT = "SESSION_ABORT"
    TRIAL_ARM = "TRIAL_ARM"
    TRIAL_START_AT = "TRIAL_START_AT"
    TRIAL_STATE = "TRIAL_STATE"
    TRIAL_END = "TRIAL_END"
    TRIAL_ABORT = "TRIAL_ABORT"
    SNAPSHOT = "SNAPSHOT"
    STATE_UPDATE = "STATE_UPDATE"
    PARAM_UPDATE = "PARAM_UPDATE"
    ROLE_STATUS = "ROLE_STATUS"
    CLIENT_STATUS = "CLIENT_STATUS"
    EVENT_REPORT = "EVENT_REPORT"
    RESULT_REPORT = "RESULT_REPORT"
    DATA_CHUNK = "DATA_CHUNK"
    MARKER = "MARKER"
    ACK = "ACK"
    NACK = "NACK"
    RETRY_NOTICE = "RETRY_NOTICE"


class Priority(StrEnum):
    LOW = "low"
    NORMAL = "normal"
    HIGH = "high"
    CRITICAL = "critical"


class ClientStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    CONNECTED = "CONNECTED"
    REGISTERED = "REGISTERED"
    SYNCED = "SYNCED"
    READY = "READY"
    RUNNING = "RUNNING"
    DEGRADED = "DEGRADED"
    RECONNECTING = "RECONNECTING"
    DISCONNECTED = "DISCONNECTED"
    REJECTED = "REJECTED"


class SessionState(StrEnum):
    IDLE = "IDLE"
    WAITING_CLIENTS = "WAITING_CLIENTS"
    READY = "READY"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    DEGRADED = "DEGRADED"
    STOPPING = "STOPPING"
    STOPPED = "STOPPED"
    ABORTED = "ABORTED"


class ErrorCode(StrEnum):
    DISCOVERY_FAILED = "DISCOVERY_FAILED"
    SERVER_NOT_REACHABLE = "SERVER_NOT_REACHABLE"
    CONTROL_CONNECT_FAILED = "CONTROL_CONNECT_FAILED"
    PUB_CHANNEL_FAILED = "PUB_CHANNEL_FAILED"
    VERSION_MISMATCH = "VERSION_MISMATCH"
    DUPLICATE_CLIENT_ID = "DUPLICATE_CLIENT_ID"
    AUTH_FAILED = "AUTH_FAILED"
    MISSING_REQUIRED_ROLE = "MISSING_REQUIRED_ROLE"
    CLOCK_SKEW_TOO_LARGE = "CLOCK_SKEW_TOO_LARGE"
    LATENCY_EXCEEDS_LIMIT = "LATENCY_EXCEEDS_LIMIT"
    QUEUE_OVERFLOW = "QUEUE_OVERFLOW"
    ACK_TIMEOUT = "ACK_TIMEOUT"
